name: dicoding_event
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fpdart: ^1.1.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
